application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      101APICONSOLE:
        license: Apache-2.0
        actions:
          apurba-action:
            function: actions/apurba-action/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: false
          apurba-cloud:
            function: actions/apurba-cloud/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true
